

      module PipelineGlobals
c               Use the various object definition routines
      use TiltedRingMod
      use DataCubeMod
      use BeamMod
      use ParameterVectorMod
      use SoFiACatalogueMod
      use GalaxyObjDictMode

      implicit none

      Type PipelineAnalysisFlags
        integer CoreCodeSwitch
        integer NoiseSource
        integer CenterSource
        integer ShapeSource
        integer SizeSource
        integer SysVelSource
        integer ProfileEstimateSource
        integer MomentMapsSource
        integer LikelihoodSwitch
        integer ModelTypeSwitch
        integer MinimizationSwitch
        integer VSysSource
        integer Linear_Log_SDSwitch

        integer CatFlag
      end Type




      Type(PipelineAnalysisFlags) PFlags
      Type(DataCube) ObservedDC, DataCubeMask       !Input to the code
      Type(DataCube) ModelDC                        !Generated by the code
      Type(DataCube) MaskedObservedDC
      Type(DataCube) SecondaryObservedDC
      Type(DataCube) ObservedMaps,ModelMaps,ResidualMaps
      Type(DataCube) ModelPVMaps

      real,ALLOCATABLE :: ObservedVelocityProfile(:,:)
      real,ALLOCATABLE :: RadGrid(:) !A grid of radii when the user specifies the rings
    

      Type(TiltedRingModel) ModelTiltedRing

      Type(TiltedRingFittingOptions) TR_FittingOptions

      Type(Beam2D) ObservedBeam, SecondaryBeam

      Type(ParameterVector) PVIni,PVModel, PV_FirstFit

      Type(SoFiACat) SCatalogue, SCatLocal

      Type(GalaxyDictionary) GalaxyDict

      integer idum


      integer MomentMapSwitch   !Switch to determine how the moment maps are obtained.
                                !0==calculated from masked cube, 1==loaded from file
                                !3==constructed from diff res cube/mask combo
      integer PreAnalysisSwitch !Switch to determine mode of preanalysis preprocessing
                                !1==Get moment maps + velocity profile
      integer FixtureOnlySwitch !If 1, stop right after DumpFittingFixture is
                                !called (skip GalaxyFit). Used to re-derive a
                                !fresh initial-guess fixture for a bootstrap
                                !realization without paying for the optimizer.
                                !Defaults to 0 (normal full-fit behaviour).
      integer ProbeSwitch       !If 1, right after the normal GalaxyFit_Simple
                                !setup (ModelDC/PVModel/beam kernel allocated)
                                !but before the optimizer runs, read probe
                                !parameter vectors from probe_params.txt and
                                !evaluate TiltedRingModelComparison once per
                                !vector with a fixed, reset RNG seed, printing
                                !chi2 for each, then stop. Used to directly
                                !compare Fortran's objective function against
                                !the JS port's at specific parameter points.
                                !Defaults to 0 (normal full-fit behaviour).
      integer TraceSwitch       !If 1, TiltedRingModelComparison prints one
                                !line per call: call counter, idum (RNG state
                                !AFTER particle placement for this call), chi2,
                                !and PA (TestParams(4)). Investigative-only --
                                !used to pair against an identical JS-side
                                !trace and find the exact call where the two
                                !ports' trajectories first diverge.
                                !Defaults to 0 (normal full-fit behaviour).
      integer DumpFixtureSwitch !If 1, dump diskfit_fixture.json and (after
                                !GalaxyFit) model_cube_bestfit.json -- the
                                !state the DCP/JS legs consume. Only the ONE
                                !initial fit (BSSwitch=0) on a UseDCP=1 config
                                !should set this; every other call (in
                                !particular fortran-local's own per-realization
                                !bootstrap fits) leaves it 0, since nothing on
                                !that path reads these files back.
                                !Defaults to 0 (no dump).


      character(500) MainFolderPath, CubeletFolder,BaseName
      character(500) ObjectBaseName,DataCubeFile
      character(500) MaskName,MapNames(0:2)
      character(500) ProfileName
      character(500) CatalogueFile,OutCatName
      character(500) FittingOptionsFile

      character(500) TempCubeFile
      character(500) TempMaskFile,TempMapNames(0:2)
      character(500) SecondaryCubeFile,SecondaryMaskFile

      character(700) MainOutputFolder

      real IniGuessWidth
      real tol, ftol

      integer PID,nProcessors
      integer,parameter :: Primary=0

      integer Version

      real,parameter,dimension(2) :: VRotLims=[0.,400.]
      real,dimension(2) :: LogSDLims
      real,dimension(2) :: LinSDLims
      real,parameter,dimension(2) :: LinSDLims_MSol=[0.1,50.]


      real,parameter,dimension(2) :: SizeLims=[2.,10.]

      real :: NoiseSigmaLim

      end module PipelineGlobals
