'use strict';

// AUTO-GENERATED by verify/extract_opcosts.js -- do not hand-edit.
// Regenerate with: node verify/extract_opcosts.js
// See that file's header and FFTW3JS/README.md for what this data means
// and the scope boundary (ordinary rank-2 r2c/c2r only; R2HCII/HC2RIII and
// DHT/REDFT/RODFT-only families excluded).
//
// Each entry: { name, registrationIndex, structType, group, kind, radix,
//               ops: {add,mul,fma,other}, via }
// registrationIndex is literal SOLVTAB array order (source order), LOWEST
// first. FFTW's planner tries solvers in REVERSE of this (LIFO -- most
// recently registered first); chooseDecomposition.js does that reversal.

exports.complexCodelets = [
  {
    "name": "n1_2",
    "registrationIndex": 0,
    "structType": "kdft_desc",
    "group": "n1",
    "kind": "DFT",
    "radix": 2,
    "ops": {
      "add": 4,
      "mul": 0,
      "fma": 0,
      "other": 0
    },
    "via": null
  },
  {
    "name": "n1_3",
    "registrationIndex": 1,
    "structType": "kdft_desc",
    "group": "n1",
    "kind": "DFT",
    "radix": 3,
    "ops": {
      "add": 10,
      "mul": 2,
      "fma": 2,
      "other": 0
    },
    "via": null
  },
  {
    "name": "n1_4",
    "registrationIndex": 2,
    "structType": "kdft_desc",
    "group": "n1",
    "kind": "DFT",
    "radix": 4,
    "ops": {
      "add": 16,
      "mul": 0,
      "fma": 0,
      "other": 0
    },
    "via": null
  },
  {
    "name": "n1_5",
    "registrationIndex": 3,
    "structType": "kdft_desc",
    "group": "n1",
    "kind": "DFT",
    "radix": 5,
    "ops": {
      "add": 26,
      "mul": 6,
      "fma": 6,
      "other": 0
    },
    "via": null
  },
  {
    "name": "n1_6",
    "registrationIndex": 4,
    "structType": "kdft_desc",
    "group": "n1",
    "kind": "DFT",
    "radix": 6,
    "ops": {
      "add": 32,
      "mul": 4,
      "fma": 4,
      "other": 0
    },
    "via": null
  },
  {
    "name": "n1_7",
    "registrationIndex": 5,
    "structType": "kdft_desc",
    "group": "n1",
    "kind": "DFT",
    "radix": 7,
    "ops": {
      "add": 36,
      "mul": 12,
      "fma": 24,
      "other": 0
    },
    "via": null
  },
  {
    "name": "n1_8",
    "registrationIndex": 6,
    "structType": "kdft_desc",
    "group": "n1",
    "kind": "DFT",
    "radix": 8,
    "ops": {
      "add": 52,
      "mul": 4,
      "fma": 0,
      "other": 0
    },
    "via": null
  },
  {
    "name": "n1_9",
    "registrationIndex": 7,
    "structType": "kdft_desc",
    "group": "n1",
    "kind": "DFT",
    "radix": 9,
    "ops": {
      "add": 60,
      "mul": 20,
      "fma": 20,
      "other": 0
    },
    "via": null
  },
  {
    "name": "n1_10",
    "registrationIndex": 8,
    "structType": "kdft_desc",
    "group": "n1",
    "kind": "DFT",
    "radix": 10,
    "ops": {
      "add": 72,
      "mul": 12,
      "fma": 12,
      "other": 0
    },
    "via": null
  },
  {
    "name": "n1_11",
    "registrationIndex": 9,
    "structType": "kdft_desc",
    "group": "n1",
    "kind": "DFT",
    "radix": 11,
    "ops": {
      "add": 60,
      "mul": 20,
      "fma": 80,
      "other": 0
    },
    "via": null
  },
  {
    "name": "n1_12",
    "registrationIndex": 10,
    "structType": "kdft_desc",
    "group": "n1",
    "kind": "DFT",
    "radix": 12,
    "ops": {
      "add": 88,
      "mul": 8,
      "fma": 8,
      "other": 0
    },
    "via": null
  },
  {
    "name": "n1_13",
    "registrationIndex": 11,
    "structType": "kdft_desc",
    "group": "n1",
    "kind": "DFT",
    "radix": 13,
    "ops": {
      "add": 138,
      "mul": 30,
      "fma": 38,
      "other": 0
    },
    "via": null
  },
  {
    "name": "n1_14",
    "registrationIndex": 12,
    "structType": "kdft_desc",
    "group": "n1",
    "kind": "DFT",
    "radix": 14,
    "ops": {
      "add": 100,
      "mul": 24,
      "fma": 48,
      "other": 0
    },
    "via": null
  },
  {
    "name": "n1_15",
    "registrationIndex": 13,
    "structType": "kdft_desc",
    "group": "n1",
    "kind": "DFT",
    "radix": 15,
    "ops": {
      "add": 128,
      "mul": 28,
      "fma": 28,
      "other": 0
    },
    "via": null
  },
  {
    "name": "n1_16",
    "registrationIndex": 14,
    "structType": "kdft_desc",
    "group": "n1",
    "kind": "DFT",
    "radix": 16,
    "ops": {
      "add": 136,
      "mul": 16,
      "fma": 8,
      "other": 0
    },
    "via": null
  },
  {
    "name": "n1_32",
    "registrationIndex": 15,
    "structType": "kdft_desc",
    "group": "n1",
    "kind": "DFT",
    "radix": 32,
    "ops": {
      "add": 340,
      "mul": 52,
      "fma": 32,
      "other": 0
    },
    "via": null
  },
  {
    "name": "n1_64",
    "registrationIndex": 16,
    "structType": "kdft_desc",
    "group": "n1",
    "kind": "DFT",
    "radix": 64,
    "ops": {
      "add": 808,
      "mul": 144,
      "fma": 104,
      "other": 0
    },
    "via": null
  },
  {
    "name": "n1_20",
    "registrationIndex": 17,
    "structType": "kdft_desc",
    "group": "n1",
    "kind": "DFT",
    "radix": 20,
    "ops": {
      "add": 184,
      "mul": 24,
      "fma": 24,
      "other": 0
    },
    "via": null
  },
  {
    "name": "n1_25",
    "registrationIndex": 18,
    "structType": "kdft_desc",
    "group": "n1",
    "kind": "DFT",
    "radix": 25,
    "ops": {
      "add": 260,
      "mul": 92,
      "fma": 92,
      "other": 0
    },
    "via": null
  },
  {
    "name": "t1_2",
    "registrationIndex": 19,
    "structType": "ct_desc",
    "group": "t1",
    "kind": "DFT",
    "radix": 2,
    "ops": {
      "add": 4,
      "mul": 2,
      "fma": 2,
      "other": 0
    },
    "via": null
  },
  {
    "name": "t1_3",
    "registrationIndex": 20,
    "structType": "ct_desc",
    "group": "t1",
    "kind": "DFT",
    "radix": 3,
    "ops": {
      "add": 10,
      "mul": 6,
      "fma": 6,
      "other": 0
    },
    "via": null
  },
  {
    "name": "t1_4",
    "registrationIndex": 21,
    "structType": "ct_desc",
    "group": "t1",
    "kind": "DFT",
    "radix": 4,
    "ops": {
      "add": 16,
      "mul": 6,
      "fma": 6,
      "other": 0
    },
    "via": null
  },
  {
    "name": "t1_5",
    "registrationIndex": 22,
    "structType": "ct_desc",
    "group": "t1",
    "kind": "DFT",
    "radix": 5,
    "ops": {
      "add": 26,
      "mul": 14,
      "fma": 14,
      "other": 0
    },
    "via": null
  },
  {
    "name": "t1_6",
    "registrationIndex": 23,
    "structType": "ct_desc",
    "group": "t1",
    "kind": "DFT",
    "radix": 6,
    "ops": {
      "add": 32,
      "mul": 14,
      "fma": 14,
      "other": 0
    },
    "via": null
  },
  {
    "name": "t1_7",
    "registrationIndex": 24,
    "structType": "ct_desc",
    "group": "t1",
    "kind": "DFT",
    "radix": 7,
    "ops": {
      "add": 36,
      "mul": 24,
      "fma": 36,
      "other": 0
    },
    "via": null
  },
  {
    "name": "t1_8",
    "registrationIndex": 25,
    "structType": "ct_desc",
    "group": "t1",
    "kind": "DFT",
    "radix": 8,
    "ops": {
      "add": 52,
      "mul": 18,
      "fma": 14,
      "other": 0
    },
    "via": null
  },
  {
    "name": "t1_9",
    "registrationIndex": 26,
    "structType": "ct_desc",
    "group": "t1",
    "kind": "DFT",
    "radix": 9,
    "ops": {
      "add": 60,
      "mul": 36,
      "fma": 36,
      "other": 0
    },
    "via": null
  },
  {
    "name": "t1_10",
    "registrationIndex": 27,
    "structType": "ct_desc",
    "group": "t1",
    "kind": "DFT",
    "radix": 10,
    "ops": {
      "add": 72,
      "mul": 30,
      "fma": 30,
      "other": 0
    },
    "via": null
  },
  {
    "name": "t1_12",
    "registrationIndex": 28,
    "structType": "ct_desc",
    "group": "t1",
    "kind": "DFT",
    "radix": 12,
    "ops": {
      "add": 88,
      "mul": 30,
      "fma": 30,
      "other": 0
    },
    "via": null
  },
  {
    "name": "t1_15",
    "registrationIndex": 29,
    "structType": "ct_desc",
    "group": "t1",
    "kind": "DFT",
    "radix": 15,
    "ops": {
      "add": 128,
      "mul": 56,
      "fma": 56,
      "other": 0
    },
    "via": null
  },
  {
    "name": "t1_16",
    "registrationIndex": 30,
    "structType": "ct_desc",
    "group": "t1",
    "kind": "DFT",
    "radix": 16,
    "ops": {
      "add": 136,
      "mul": 46,
      "fma": 38,
      "other": 0
    },
    "via": null
  },
  {
    "name": "t1_32",
    "registrationIndex": 31,
    "structType": "ct_desc",
    "group": "t1",
    "kind": "DFT",
    "radix": 32,
    "ops": {
      "add": 340,
      "mul": 114,
      "fma": 94,
      "other": 0
    },
    "via": null
  },
  {
    "name": "t1_64",
    "registrationIndex": 32,
    "structType": "ct_desc",
    "group": "t1",
    "kind": "DFT",
    "radix": 64,
    "ops": {
      "add": 808,
      "mul": 270,
      "fma": 230,
      "other": 0
    },
    "via": null
  },
  {
    "name": "t1_20",
    "registrationIndex": 33,
    "structType": "ct_desc",
    "group": "t1",
    "kind": "DFT",
    "radix": 20,
    "ops": {
      "add": 184,
      "mul": 62,
      "fma": 62,
      "other": 0
    },
    "via": null
  },
  {
    "name": "t1_25",
    "registrationIndex": 34,
    "structType": "ct_desc",
    "group": "t1",
    "kind": "DFT",
    "radix": 25,
    "ops": {
      "add": 260,
      "mul": 140,
      "fma": 140,
      "other": 0
    },
    "via": null
  },
  {
    "name": "t2_4",
    "registrationIndex": 35,
    "structType": "ct_desc",
    "group": "t2",
    "kind": "DFT",
    "radix": 4,
    "ops": {
      "add": 16,
      "mul": 8,
      "fma": 8,
      "other": 0
    },
    "via": null
  },
  {
    "name": "t2_8",
    "registrationIndex": 36,
    "structType": "ct_desc",
    "group": "t2",
    "kind": "DFT",
    "radix": 8,
    "ops": {
      "add": 56,
      "mul": 26,
      "fma": 18,
      "other": 0
    },
    "via": null
  },
  {
    "name": "t2_16",
    "registrationIndex": 37,
    "structType": "ct_desc",
    "group": "t2",
    "kind": "DFT",
    "radix": 16,
    "ops": {
      "add": 156,
      "mul": 68,
      "fma": 40,
      "other": 0
    },
    "via": null
  },
  {
    "name": "t2_32",
    "registrationIndex": 38,
    "structType": "ct_desc",
    "group": "t2",
    "kind": "DFT",
    "radix": 32,
    "ops": {
      "add": 376,
      "mul": 168,
      "fma": 112,
      "other": 0
    },
    "via": null
  },
  {
    "name": "t2_64",
    "registrationIndex": 39,
    "structType": "ct_desc",
    "group": "t2",
    "kind": "DFT",
    "radix": 64,
    "ops": {
      "add": 880,
      "mul": 386,
      "fma": 274,
      "other": 0
    },
    "via": null
  },
  {
    "name": "t2_5",
    "registrationIndex": 40,
    "structType": "ct_desc",
    "group": "t2",
    "kind": "DFT",
    "radix": 5,
    "ops": {
      "add": 30,
      "mul": 18,
      "fma": 14,
      "other": 0
    },
    "via": null
  },
  {
    "name": "t2_10",
    "registrationIndex": 41,
    "structType": "ct_desc",
    "group": "t2",
    "kind": "DFT",
    "radix": 10,
    "ops": {
      "add": 76,
      "mul": 42,
      "fma": 38,
      "other": 0
    },
    "via": null
  },
  {
    "name": "t2_20",
    "registrationIndex": 42,
    "structType": "ct_desc",
    "group": "t2",
    "kind": "DFT",
    "radix": 20,
    "ops": {
      "add": 204,
      "mul": 92,
      "fma": 72,
      "other": 0
    },
    "via": null
  },
  {
    "name": "t2_25",
    "registrationIndex": 43,
    "structType": "ct_desc",
    "group": "t2",
    "kind": "DFT",
    "radix": 25,
    "ops": {
      "add": 280,
      "mul": 180,
      "fma": 160,
      "other": 0
    },
    "via": null
  }
];

exports.q1Codelets = [
  {
    "name": "q1_2",
    "registrationIndex": 44,
    "structType": "ct_desc",
    "group": "q1",
    "kind": "DFT",
    "radix": 2,
    "ops": {
      "add": 8,
      "mul": 4,
      "fma": 4,
      "other": 0
    },
    "via": null
  },
  {
    "name": "q1_4",
    "registrationIndex": 45,
    "structType": "ct_desc",
    "group": "q1",
    "kind": "DFT",
    "radix": 4,
    "ops": {
      "add": 64,
      "mul": 24,
      "fma": 24,
      "other": 0
    },
    "via": null
  },
  {
    "name": "q1_8",
    "registrationIndex": 46,
    "structType": "ct_desc",
    "group": "q1",
    "kind": "DFT",
    "radix": 8,
    "ops": {
      "add": 416,
      "mul": 144,
      "fma": 112,
      "other": 0
    },
    "via": null
  },
  {
    "name": "q1_3",
    "registrationIndex": 47,
    "structType": "ct_desc",
    "group": "q1",
    "kind": "DFT",
    "radix": 3,
    "ops": {
      "add": 30,
      "mul": 18,
      "fma": 18,
      "other": 0
    },
    "via": null
  },
  {
    "name": "q1_5",
    "registrationIndex": 48,
    "structType": "ct_desc",
    "group": "q1",
    "kind": "DFT",
    "radix": 5,
    "ops": {
      "add": 130,
      "mul": 70,
      "fma": 70,
      "other": 0
    },
    "via": null
  },
  {
    "name": "q1_6",
    "registrationIndex": 49,
    "structType": "ct_desc",
    "group": "q1",
    "kind": "DFT",
    "radix": 6,
    "ops": {
      "add": 192,
      "mul": 84,
      "fma": 84,
      "other": 0
    },
    "via": null
  }
];

exports.realForwardCodelets = [
  {
    "name": "r2cf_2",
    "registrationIndex": 0,
    "structType": "kr2c_desc",
    "group": "r2cf",
    "kind": "R2HC",
    "radix": 2,
    "ops": {
      "add": 2,
      "mul": 0,
      "fma": 0,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cf_3",
    "registrationIndex": 1,
    "structType": "kr2c_desc",
    "group": "r2cf",
    "kind": "R2HC",
    "radix": 3,
    "ops": {
      "add": 3,
      "mul": 1,
      "fma": 1,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cf_4",
    "registrationIndex": 2,
    "structType": "kr2c_desc",
    "group": "r2cf",
    "kind": "R2HC",
    "radix": 4,
    "ops": {
      "add": 6,
      "mul": 0,
      "fma": 0,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cf_5",
    "registrationIndex": 3,
    "structType": "kr2c_desc",
    "group": "r2cf",
    "kind": "R2HC",
    "radix": 5,
    "ops": {
      "add": 9,
      "mul": 3,
      "fma": 3,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cf_6",
    "registrationIndex": 4,
    "structType": "kr2c_desc",
    "group": "r2cf",
    "kind": "R2HC",
    "radix": 6,
    "ops": {
      "add": 12,
      "mul": 2,
      "fma": 2,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cf_7",
    "registrationIndex": 5,
    "structType": "kr2c_desc",
    "group": "r2cf",
    "kind": "R2HC",
    "radix": 7,
    "ops": {
      "add": 12,
      "mul": 6,
      "fma": 12,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cf_8",
    "registrationIndex": 6,
    "structType": "kr2c_desc",
    "group": "r2cf",
    "kind": "R2HC",
    "radix": 8,
    "ops": {
      "add": 20,
      "mul": 2,
      "fma": 0,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cf_9",
    "registrationIndex": 7,
    "structType": "kr2c_desc",
    "group": "r2cf",
    "kind": "R2HC",
    "radix": 9,
    "ops": {
      "add": 21,
      "mul": 9,
      "fma": 17,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cf_10",
    "registrationIndex": 8,
    "structType": "kr2c_desc",
    "group": "r2cf",
    "kind": "R2HC",
    "radix": 10,
    "ops": {
      "add": 28,
      "mul": 6,
      "fma": 6,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cf_11",
    "registrationIndex": 9,
    "structType": "kr2c_desc",
    "group": "r2cf",
    "kind": "R2HC",
    "radix": 11,
    "ops": {
      "add": 20,
      "mul": 10,
      "fma": 40,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cf_12",
    "registrationIndex": 10,
    "structType": "kr2c_desc",
    "group": "r2cf",
    "kind": "R2HC",
    "radix": 12,
    "ops": {
      "add": 34,
      "mul": 4,
      "fma": 4,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cf_13",
    "registrationIndex": 11,
    "structType": "kr2c_desc",
    "group": "r2cf",
    "kind": "R2HC",
    "radix": 13,
    "ops": {
      "add": 57,
      "mul": 15,
      "fma": 19,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cf_14",
    "registrationIndex": 12,
    "structType": "kr2c_desc",
    "group": "r2cf",
    "kind": "R2HC",
    "radix": 14,
    "ops": {
      "add": 38,
      "mul": 12,
      "fma": 24,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cf_15",
    "registrationIndex": 13,
    "structType": "kr2c_desc",
    "group": "r2cf",
    "kind": "R2HC",
    "radix": 15,
    "ops": {
      "add": 50,
      "mul": 11,
      "fma": 14,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cf_16",
    "registrationIndex": 14,
    "structType": "kr2c_desc",
    "group": "r2cf",
    "kind": "R2HC",
    "radix": 16,
    "ops": {
      "add": 54,
      "mul": 8,
      "fma": 4,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cf_32",
    "registrationIndex": 15,
    "structType": "kr2c_desc",
    "group": "r2cf",
    "kind": "R2HC",
    "radix": 32,
    "ops": {
      "add": 140,
      "mul": 26,
      "fma": 16,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cf_64",
    "registrationIndex": 16,
    "structType": "kr2c_desc",
    "group": "r2cf",
    "kind": "R2HC",
    "radix": 64,
    "ops": {
      "add": 342,
      "mul": 72,
      "fma": 52,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cf_128",
    "registrationIndex": 17,
    "structType": "kr2c_desc",
    "group": "r2cf",
    "kind": "R2HC",
    "radix": 128,
    "ops": {
      "add": 812,
      "mul": 186,
      "fma": 144,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cf_20",
    "registrationIndex": 18,
    "structType": "kr2c_desc",
    "group": "r2cf",
    "kind": "R2HC",
    "radix": 20,
    "ops": {
      "add": 74,
      "mul": 12,
      "fma": 12,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cf_25",
    "registrationIndex": 19,
    "structType": "kr2c_desc",
    "group": "r2cf",
    "kind": "R2HC",
    "radix": 25,
    "ops": {
      "add": 117,
      "mul": 57,
      "fma": 83,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hf_2",
    "registrationIndex": 20,
    "structType": "hc2hc_desc",
    "group": "hf",
    "kind": "R2HC",
    "radix": 2,
    "ops": {
      "add": 4,
      "mul": 2,
      "fma": 2,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hf_3",
    "registrationIndex": 21,
    "structType": "hc2hc_desc",
    "group": "hf",
    "kind": "R2HC",
    "radix": 3,
    "ops": {
      "add": 10,
      "mul": 6,
      "fma": 6,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hf_4",
    "registrationIndex": 22,
    "structType": "hc2hc_desc",
    "group": "hf",
    "kind": "R2HC",
    "radix": 4,
    "ops": {
      "add": 16,
      "mul": 6,
      "fma": 6,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hf_5",
    "registrationIndex": 23,
    "structType": "hc2hc_desc",
    "group": "hf",
    "kind": "R2HC",
    "radix": 5,
    "ops": {
      "add": 26,
      "mul": 14,
      "fma": 14,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hf_6",
    "registrationIndex": 24,
    "structType": "hc2hc_desc",
    "group": "hf",
    "kind": "R2HC",
    "radix": 6,
    "ops": {
      "add": 32,
      "mul": 14,
      "fma": 14,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hf_7",
    "registrationIndex": 25,
    "structType": "hc2hc_desc",
    "group": "hf",
    "kind": "R2HC",
    "radix": 7,
    "ops": {
      "add": 36,
      "mul": 24,
      "fma": 36,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hf_8",
    "registrationIndex": 26,
    "structType": "hc2hc_desc",
    "group": "hf",
    "kind": "R2HC",
    "radix": 8,
    "ops": {
      "add": 52,
      "mul": 18,
      "fma": 14,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hf_9",
    "registrationIndex": 27,
    "structType": "hc2hc_desc",
    "group": "hf",
    "kind": "R2HC",
    "radix": 9,
    "ops": {
      "add": 60,
      "mul": 36,
      "fma": 36,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hf_10",
    "registrationIndex": 28,
    "structType": "hc2hc_desc",
    "group": "hf",
    "kind": "R2HC",
    "radix": 10,
    "ops": {
      "add": 72,
      "mul": 30,
      "fma": 30,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hf_12",
    "registrationIndex": 29,
    "structType": "hc2hc_desc",
    "group": "hf",
    "kind": "R2HC",
    "radix": 12,
    "ops": {
      "add": 88,
      "mul": 30,
      "fma": 30,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hf_15",
    "registrationIndex": 30,
    "structType": "hc2hc_desc",
    "group": "hf",
    "kind": "R2HC",
    "radix": 15,
    "ops": {
      "add": 128,
      "mul": 56,
      "fma": 56,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hf_16",
    "registrationIndex": 31,
    "structType": "hc2hc_desc",
    "group": "hf",
    "kind": "R2HC",
    "radix": 16,
    "ops": {
      "add": 136,
      "mul": 46,
      "fma": 38,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hf_32",
    "registrationIndex": 32,
    "structType": "hc2hc_desc",
    "group": "hf",
    "kind": "R2HC",
    "radix": 32,
    "ops": {
      "add": 340,
      "mul": 114,
      "fma": 94,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hf_64",
    "registrationIndex": 33,
    "structType": "hc2hc_desc",
    "group": "hf",
    "kind": "R2HC",
    "radix": 64,
    "ops": {
      "add": 808,
      "mul": 270,
      "fma": 230,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hf_20",
    "registrationIndex": 34,
    "structType": "hc2hc_desc",
    "group": "hf",
    "kind": "R2HC",
    "radix": 20,
    "ops": {
      "add": 184,
      "mul": 62,
      "fma": 62,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hf_25",
    "registrationIndex": 35,
    "structType": "hc2hc_desc",
    "group": "hf",
    "kind": "R2HC",
    "radix": 25,
    "ops": {
      "add": 260,
      "mul": 140,
      "fma": 140,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hf2_4",
    "registrationIndex": 36,
    "structType": "hc2hc_desc",
    "group": "hf2",
    "kind": "R2HC",
    "radix": 4,
    "ops": {
      "add": 16,
      "mul": 8,
      "fma": 8,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hf2_8",
    "registrationIndex": 37,
    "structType": "hc2hc_desc",
    "group": "hf2",
    "kind": "R2HC",
    "radix": 8,
    "ops": {
      "add": 56,
      "mul": 26,
      "fma": 18,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hf2_16",
    "registrationIndex": 38,
    "structType": "hc2hc_desc",
    "group": "hf2",
    "kind": "R2HC",
    "radix": 16,
    "ops": {
      "add": 156,
      "mul": 68,
      "fma": 40,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hf2_32",
    "registrationIndex": 39,
    "structType": "hc2hc_desc",
    "group": "hf2",
    "kind": "R2HC",
    "radix": 32,
    "ops": {
      "add": 376,
      "mul": 168,
      "fma": 112,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hf2_5",
    "registrationIndex": 40,
    "structType": "hc2hc_desc",
    "group": "hf2",
    "kind": "R2HC",
    "radix": 5,
    "ops": {
      "add": 30,
      "mul": 18,
      "fma": 14,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hf2_20",
    "registrationIndex": 41,
    "structType": "hc2hc_desc",
    "group": "hf2",
    "kind": "R2HC",
    "radix": 20,
    "ops": {
      "add": 204,
      "mul": 92,
      "fma": 72,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hf2_25",
    "registrationIndex": 42,
    "structType": "hc2hc_desc",
    "group": "hf2",
    "kind": "R2HC",
    "radix": 25,
    "ops": {
      "add": 280,
      "mul": 180,
      "fma": 160,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hc2cf_2",
    "registrationIndex": 43,
    "structType": "hc2c_desc",
    "group": "hc2cf",
    "kind": "R2HC",
    "radix": 2,
    "ops": {
      "add": 4,
      "mul": 2,
      "fma": 2,
      "other": 0
    },
    "via": "HC2C_VIA_RDFT"
  },
  {
    "name": "hc2cf_4",
    "registrationIndex": 44,
    "structType": "hc2c_desc",
    "group": "hc2cf",
    "kind": "R2HC",
    "radix": 4,
    "ops": {
      "add": 16,
      "mul": 6,
      "fma": 6,
      "other": 0
    },
    "via": "HC2C_VIA_RDFT"
  },
  {
    "name": "hc2cf_6",
    "registrationIndex": 45,
    "structType": "hc2c_desc",
    "group": "hc2cf",
    "kind": "R2HC",
    "radix": 6,
    "ops": {
      "add": 32,
      "mul": 14,
      "fma": 14,
      "other": 0
    },
    "via": "HC2C_VIA_RDFT"
  },
  {
    "name": "hc2cf_8",
    "registrationIndex": 46,
    "structType": "hc2c_desc",
    "group": "hc2cf",
    "kind": "R2HC",
    "radix": 8,
    "ops": {
      "add": 52,
      "mul": 18,
      "fma": 14,
      "other": 0
    },
    "via": "HC2C_VIA_RDFT"
  },
  {
    "name": "hc2cf_10",
    "registrationIndex": 47,
    "structType": "hc2c_desc",
    "group": "hc2cf",
    "kind": "R2HC",
    "radix": 10,
    "ops": {
      "add": 72,
      "mul": 30,
      "fma": 30,
      "other": 0
    },
    "via": "HC2C_VIA_RDFT"
  },
  {
    "name": "hc2cf_12",
    "registrationIndex": 48,
    "structType": "hc2c_desc",
    "group": "hc2cf",
    "kind": "R2HC",
    "radix": 12,
    "ops": {
      "add": 88,
      "mul": 30,
      "fma": 30,
      "other": 0
    },
    "via": "HC2C_VIA_RDFT"
  },
  {
    "name": "hc2cf_16",
    "registrationIndex": 49,
    "structType": "hc2c_desc",
    "group": "hc2cf",
    "kind": "R2HC",
    "radix": 16,
    "ops": {
      "add": 136,
      "mul": 46,
      "fma": 38,
      "other": 0
    },
    "via": "HC2C_VIA_RDFT"
  },
  {
    "name": "hc2cf_32",
    "registrationIndex": 50,
    "structType": "hc2c_desc",
    "group": "hc2cf",
    "kind": "R2HC",
    "radix": 32,
    "ops": {
      "add": 340,
      "mul": 114,
      "fma": 94,
      "other": 0
    },
    "via": "HC2C_VIA_RDFT"
  },
  {
    "name": "hc2cf_20",
    "registrationIndex": 51,
    "structType": "hc2c_desc",
    "group": "hc2cf",
    "kind": "R2HC",
    "radix": 20,
    "ops": {
      "add": 184,
      "mul": 62,
      "fma": 62,
      "other": 0
    },
    "via": "HC2C_VIA_RDFT"
  },
  {
    "name": "hc2cf2_4",
    "registrationIndex": 52,
    "structType": "hc2c_desc",
    "group": "hc2cf2",
    "kind": "R2HC",
    "radix": 4,
    "ops": {
      "add": 16,
      "mul": 8,
      "fma": 8,
      "other": 0
    },
    "via": "HC2C_VIA_RDFT"
  },
  {
    "name": "hc2cf2_8",
    "registrationIndex": 53,
    "structType": "hc2c_desc",
    "group": "hc2cf2",
    "kind": "R2HC",
    "radix": 8,
    "ops": {
      "add": 56,
      "mul": 26,
      "fma": 18,
      "other": 0
    },
    "via": "HC2C_VIA_RDFT"
  },
  {
    "name": "hc2cf2_16",
    "registrationIndex": 54,
    "structType": "hc2c_desc",
    "group": "hc2cf2",
    "kind": "R2HC",
    "radix": 16,
    "ops": {
      "add": 156,
      "mul": 68,
      "fma": 40,
      "other": 0
    },
    "via": "HC2C_VIA_RDFT"
  },
  {
    "name": "hc2cf2_32",
    "registrationIndex": 55,
    "structType": "hc2c_desc",
    "group": "hc2cf2",
    "kind": "R2HC",
    "radix": 32,
    "ops": {
      "add": 376,
      "mul": 168,
      "fma": 112,
      "other": 0
    },
    "via": "HC2C_VIA_RDFT"
  },
  {
    "name": "hc2cf2_20",
    "registrationIndex": 56,
    "structType": "hc2c_desc",
    "group": "hc2cf2",
    "kind": "R2HC",
    "radix": 20,
    "ops": {
      "add": 204,
      "mul": 92,
      "fma": 72,
      "other": 0
    },
    "via": "HC2C_VIA_RDFT"
  },
  {
    "name": "hc2cfdft_2",
    "registrationIndex": 57,
    "structType": "hc2c_desc",
    "group": "hc2cfdft",
    "kind": "R2HC",
    "radix": 2,
    "ops": {
      "add": 8,
      "mul": 6,
      "fma": 2,
      "other": 0
    },
    "via": "HC2C_VIA_DFT"
  },
  {
    "name": "hc2cfdft_4",
    "registrationIndex": 58,
    "structType": "hc2c_desc",
    "group": "hc2cfdft",
    "kind": "R2HC",
    "radix": 4,
    "ops": {
      "add": 24,
      "mul": 14,
      "fma": 6,
      "other": 0
    },
    "via": "HC2C_VIA_DFT"
  },
  {
    "name": "hc2cfdft_6",
    "registrationIndex": 59,
    "structType": "hc2c_desc",
    "group": "hc2cfdft",
    "kind": "R2HC",
    "radix": 6,
    "ops": {
      "add": 44,
      "mul": 22,
      "fma": 14,
      "other": 0
    },
    "via": "HC2C_VIA_DFT"
  },
  {
    "name": "hc2cfdft_8",
    "registrationIndex": 60,
    "structType": "hc2c_desc",
    "group": "hc2cfdft",
    "kind": "R2HC",
    "radix": 8,
    "ops": {
      "add": 68,
      "mul": 30,
      "fma": 14,
      "other": 0
    },
    "via": "HC2C_VIA_DFT"
  },
  {
    "name": "hc2cfdft_10",
    "registrationIndex": 61,
    "structType": "hc2c_desc",
    "group": "hc2cfdft",
    "kind": "R2HC",
    "radix": 10,
    "ops": {
      "add": 92,
      "mul": 38,
      "fma": 30,
      "other": 0
    },
    "via": "HC2C_VIA_DFT"
  },
  {
    "name": "hc2cfdft_12",
    "registrationIndex": 62,
    "structType": "hc2c_desc",
    "group": "hc2cfdft",
    "kind": "R2HC",
    "radix": 12,
    "ops": {
      "add": 112,
      "mul": 46,
      "fma": 30,
      "other": 0
    },
    "via": "HC2C_VIA_DFT"
  },
  {
    "name": "hc2cfdft_16",
    "registrationIndex": 63,
    "structType": "hc2c_desc",
    "group": "hc2cfdft",
    "kind": "R2HC",
    "radix": 16,
    "ops": {
      "add": 168,
      "mul": 62,
      "fma": 38,
      "other": 0
    },
    "via": "HC2C_VIA_DFT"
  },
  {
    "name": "hc2cfdft_32",
    "registrationIndex": 64,
    "structType": "hc2c_desc",
    "group": "hc2cfdft",
    "kind": "R2HC",
    "radix": 32,
    "ops": {
      "add": 404,
      "mul": 134,
      "fma": 94,
      "other": 0
    },
    "via": "HC2C_VIA_DFT"
  },
  {
    "name": "hc2cfdft_20",
    "registrationIndex": 65,
    "structType": "hc2c_desc",
    "group": "hc2cfdft",
    "kind": "R2HC",
    "radix": 20,
    "ops": {
      "add": 224,
      "mul": 78,
      "fma": 62,
      "other": 0
    },
    "via": "HC2C_VIA_DFT"
  },
  {
    "name": "hc2cfdft2_4",
    "registrationIndex": 66,
    "structType": "hc2c_desc",
    "group": "hc2cfdft2",
    "kind": "R2HC",
    "radix": 4,
    "ops": {
      "add": 24,
      "mul": 16,
      "fma": 8,
      "other": 0
    },
    "via": "HC2C_VIA_DFT"
  },
  {
    "name": "hc2cfdft2_8",
    "registrationIndex": 67,
    "structType": "hc2c_desc",
    "group": "hc2cfdft2",
    "kind": "R2HC",
    "radix": 8,
    "ops": {
      "add": 72,
      "mul": 38,
      "fma": 18,
      "other": 0
    },
    "via": "HC2C_VIA_DFT"
  },
  {
    "name": "hc2cfdft2_16",
    "registrationIndex": 68,
    "structType": "hc2c_desc",
    "group": "hc2cfdft2",
    "kind": "R2HC",
    "radix": 16,
    "ops": {
      "add": 188,
      "mul": 84,
      "fma": 40,
      "other": 0
    },
    "via": "HC2C_VIA_DFT"
  },
  {
    "name": "hc2cfdft2_32",
    "registrationIndex": 69,
    "structType": "hc2c_desc",
    "group": "hc2cfdft2",
    "kind": "R2HC",
    "radix": 32,
    "ops": {
      "add": 440,
      "mul": 188,
      "fma": 112,
      "other": 0
    },
    "via": "HC2C_VIA_DFT"
  },
  {
    "name": "hc2cfdft2_20",
    "registrationIndex": 70,
    "structType": "hc2c_desc",
    "group": "hc2cfdft2",
    "kind": "R2HC",
    "radix": 20,
    "ops": {
      "add": 244,
      "mul": 108,
      "fma": 72,
      "other": 0
    },
    "via": "HC2C_VIA_DFT"
  }
];

exports.realBackwardCodelets = [
  {
    "name": "r2cb_2",
    "registrationIndex": 0,
    "structType": "kr2c_desc",
    "group": "r2cb",
    "kind": "HC2R",
    "radix": 2,
    "ops": {
      "add": 2,
      "mul": 0,
      "fma": 0,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cb_3",
    "registrationIndex": 1,
    "structType": "kr2c_desc",
    "group": "r2cb",
    "kind": "HC2R",
    "radix": 3,
    "ops": {
      "add": 3,
      "mul": 1,
      "fma": 1,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cb_4",
    "registrationIndex": 2,
    "structType": "kr2c_desc",
    "group": "r2cb",
    "kind": "HC2R",
    "radix": 4,
    "ops": {
      "add": 6,
      "mul": 2,
      "fma": 0,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cb_5",
    "registrationIndex": 3,
    "structType": "kr2c_desc",
    "group": "r2cb",
    "kind": "HC2R",
    "radix": 5,
    "ops": {
      "add": 8,
      "mul": 3,
      "fma": 4,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cb_6",
    "registrationIndex": 4,
    "structType": "kr2c_desc",
    "group": "r2cb",
    "kind": "HC2R",
    "radix": 6,
    "ops": {
      "add": 12,
      "mul": 2,
      "fma": 2,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cb_7",
    "registrationIndex": 5,
    "structType": "kr2c_desc",
    "group": "r2cb",
    "kind": "HC2R",
    "radix": 7,
    "ops": {
      "add": 11,
      "mul": 6,
      "fma": 13,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cb_8",
    "registrationIndex": 6,
    "structType": "kr2c_desc",
    "group": "r2cb",
    "kind": "HC2R",
    "radix": 8,
    "ops": {
      "add": 20,
      "mul": 6,
      "fma": 0,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cb_9",
    "registrationIndex": 7,
    "structType": "kr2c_desc",
    "group": "r2cb",
    "kind": "HC2R",
    "radix": 9,
    "ops": {
      "add": 22,
      "mul": 8,
      "fma": 10,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cb_10",
    "registrationIndex": 8,
    "structType": "kr2c_desc",
    "group": "r2cb",
    "kind": "HC2R",
    "radix": 10,
    "ops": {
      "add": 26,
      "mul": 6,
      "fma": 8,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cb_11",
    "registrationIndex": 9,
    "structType": "kr2c_desc",
    "group": "r2cb",
    "kind": "HC2R",
    "radix": 11,
    "ops": {
      "add": 19,
      "mul": 10,
      "fma": 41,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cb_12",
    "registrationIndex": 10,
    "structType": "kr2c_desc",
    "group": "r2cb",
    "kind": "HC2R",
    "radix": 12,
    "ops": {
      "add": 34,
      "mul": 6,
      "fma": 4,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cb_13",
    "registrationIndex": 11,
    "structType": "kr2c_desc",
    "group": "r2cb",
    "kind": "HC2R",
    "radix": 13,
    "ops": {
      "add": 56,
      "mul": 15,
      "fma": 20,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cb_14",
    "registrationIndex": 12,
    "structType": "kr2c_desc",
    "group": "r2cb",
    "kind": "HC2R",
    "radix": 14,
    "ops": {
      "add": 36,
      "mul": 12,
      "fma": 26,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cb_15",
    "registrationIndex": 13,
    "structType": "kr2c_desc",
    "group": "r2cb",
    "kind": "HC2R",
    "radix": 15,
    "ops": {
      "add": 47,
      "mul": 14,
      "fma": 17,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cb_16",
    "registrationIndex": 14,
    "structType": "kr2c_desc",
    "group": "r2cb",
    "kind": "HC2R",
    "radix": 16,
    "ops": {
      "add": 54,
      "mul": 14,
      "fma": 4,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cb_32",
    "registrationIndex": 15,
    "structType": "kr2c_desc",
    "group": "r2cb",
    "kind": "HC2R",
    "radix": 32,
    "ops": {
      "add": 140,
      "mul": 34,
      "fma": 16,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cb_64",
    "registrationIndex": 16,
    "structType": "kr2c_desc",
    "group": "r2cb",
    "kind": "HC2R",
    "radix": 64,
    "ops": {
      "add": 342,
      "mul": 82,
      "fma": 52,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cb_128",
    "registrationIndex": 17,
    "structType": "kr2c_desc",
    "group": "r2cb",
    "kind": "HC2R",
    "radix": 128,
    "ops": {
      "add": 812,
      "mul": 198,
      "fma": 144,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cb_20",
    "registrationIndex": 18,
    "structType": "kr2c_desc",
    "group": "r2cb",
    "kind": "HC2R",
    "radix": 20,
    "ops": {
      "add": 70,
      "mul": 14,
      "fma": 16,
      "other": 0
    },
    "via": null
  },
  {
    "name": "r2cb_25",
    "registrationIndex": 19,
    "structType": "kr2c_desc",
    "group": "r2cb",
    "kind": "HC2R",
    "radix": 25,
    "ops": {
      "add": 100,
      "mul": 46,
      "fma": 52,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hb_2",
    "registrationIndex": 20,
    "structType": "hc2hc_desc",
    "group": "hb",
    "kind": "HC2R",
    "radix": 2,
    "ops": {
      "add": 4,
      "mul": 2,
      "fma": 2,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hb_3",
    "registrationIndex": 21,
    "structType": "hc2hc_desc",
    "group": "hb",
    "kind": "HC2R",
    "radix": 3,
    "ops": {
      "add": 10,
      "mul": 6,
      "fma": 6,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hb_4",
    "registrationIndex": 22,
    "structType": "hc2hc_desc",
    "group": "hb",
    "kind": "HC2R",
    "radix": 4,
    "ops": {
      "add": 16,
      "mul": 6,
      "fma": 6,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hb_5",
    "registrationIndex": 23,
    "structType": "hc2hc_desc",
    "group": "hb",
    "kind": "HC2R",
    "radix": 5,
    "ops": {
      "add": 26,
      "mul": 14,
      "fma": 14,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hb_6",
    "registrationIndex": 24,
    "structType": "hc2hc_desc",
    "group": "hb",
    "kind": "HC2R",
    "radix": 6,
    "ops": {
      "add": 32,
      "mul": 14,
      "fma": 14,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hb_7",
    "registrationIndex": 25,
    "structType": "hc2hc_desc",
    "group": "hb",
    "kind": "HC2R",
    "radix": 7,
    "ops": {
      "add": 36,
      "mul": 24,
      "fma": 36,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hb_8",
    "registrationIndex": 26,
    "structType": "hc2hc_desc",
    "group": "hb",
    "kind": "HC2R",
    "radix": 8,
    "ops": {
      "add": 52,
      "mul": 18,
      "fma": 14,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hb_9",
    "registrationIndex": 27,
    "structType": "hc2hc_desc",
    "group": "hb",
    "kind": "HC2R",
    "radix": 9,
    "ops": {
      "add": 60,
      "mul": 36,
      "fma": 36,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hb_10",
    "registrationIndex": 28,
    "structType": "hc2hc_desc",
    "group": "hb",
    "kind": "HC2R",
    "radix": 10,
    "ops": {
      "add": 72,
      "mul": 30,
      "fma": 30,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hb_12",
    "registrationIndex": 29,
    "structType": "hc2hc_desc",
    "group": "hb",
    "kind": "HC2R",
    "radix": 12,
    "ops": {
      "add": 88,
      "mul": 30,
      "fma": 30,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hb_15",
    "registrationIndex": 30,
    "structType": "hc2hc_desc",
    "group": "hb",
    "kind": "HC2R",
    "radix": 15,
    "ops": {
      "add": 128,
      "mul": 56,
      "fma": 56,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hb_16",
    "registrationIndex": 31,
    "structType": "hc2hc_desc",
    "group": "hb",
    "kind": "HC2R",
    "radix": 16,
    "ops": {
      "add": 136,
      "mul": 46,
      "fma": 38,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hb_32",
    "registrationIndex": 32,
    "structType": "hc2hc_desc",
    "group": "hb",
    "kind": "HC2R",
    "radix": 32,
    "ops": {
      "add": 340,
      "mul": 114,
      "fma": 94,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hb_64",
    "registrationIndex": 33,
    "structType": "hc2hc_desc",
    "group": "hb",
    "kind": "HC2R",
    "radix": 64,
    "ops": {
      "add": 808,
      "mul": 270,
      "fma": 230,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hb_20",
    "registrationIndex": 34,
    "structType": "hc2hc_desc",
    "group": "hb",
    "kind": "HC2R",
    "radix": 20,
    "ops": {
      "add": 184,
      "mul": 62,
      "fma": 62,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hb_25",
    "registrationIndex": 35,
    "structType": "hc2hc_desc",
    "group": "hb",
    "kind": "HC2R",
    "radix": 25,
    "ops": {
      "add": 260,
      "mul": 140,
      "fma": 140,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hb2_4",
    "registrationIndex": 36,
    "structType": "hc2hc_desc",
    "group": "hb2",
    "kind": "HC2R",
    "radix": 4,
    "ops": {
      "add": 16,
      "mul": 8,
      "fma": 8,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hb2_8",
    "registrationIndex": 37,
    "structType": "hc2hc_desc",
    "group": "hb2",
    "kind": "HC2R",
    "radix": 8,
    "ops": {
      "add": 56,
      "mul": 26,
      "fma": 18,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hb2_16",
    "registrationIndex": 38,
    "structType": "hc2hc_desc",
    "group": "hb2",
    "kind": "HC2R",
    "radix": 16,
    "ops": {
      "add": 156,
      "mul": 68,
      "fma": 40,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hb2_32",
    "registrationIndex": 39,
    "structType": "hc2hc_desc",
    "group": "hb2",
    "kind": "HC2R",
    "radix": 32,
    "ops": {
      "add": 376,
      "mul": 168,
      "fma": 112,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hb2_5",
    "registrationIndex": 40,
    "structType": "hc2hc_desc",
    "group": "hb2",
    "kind": "HC2R",
    "radix": 5,
    "ops": {
      "add": 30,
      "mul": 18,
      "fma": 14,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hb2_20",
    "registrationIndex": 41,
    "structType": "hc2hc_desc",
    "group": "hb2",
    "kind": "HC2R",
    "radix": 20,
    "ops": {
      "add": 204,
      "mul": 92,
      "fma": 72,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hb2_25",
    "registrationIndex": 42,
    "structType": "hc2hc_desc",
    "group": "hb2",
    "kind": "HC2R",
    "radix": 25,
    "ops": {
      "add": 280,
      "mul": 180,
      "fma": 160,
      "other": 0
    },
    "via": null
  },
  {
    "name": "hc2cb_2",
    "registrationIndex": 43,
    "structType": "hc2c_desc",
    "group": "hc2cb",
    "kind": "HC2R",
    "radix": 2,
    "ops": {
      "add": 4,
      "mul": 2,
      "fma": 2,
      "other": 0
    },
    "via": "HC2C_VIA_RDFT"
  },
  {
    "name": "hc2cb_4",
    "registrationIndex": 44,
    "structType": "hc2c_desc",
    "group": "hc2cb",
    "kind": "HC2R",
    "radix": 4,
    "ops": {
      "add": 16,
      "mul": 6,
      "fma": 6,
      "other": 0
    },
    "via": "HC2C_VIA_RDFT"
  },
  {
    "name": "hc2cb_6",
    "registrationIndex": 45,
    "structType": "hc2c_desc",
    "group": "hc2cb",
    "kind": "HC2R",
    "radix": 6,
    "ops": {
      "add": 32,
      "mul": 14,
      "fma": 14,
      "other": 0
    },
    "via": "HC2C_VIA_RDFT"
  },
  {
    "name": "hc2cb_8",
    "registrationIndex": 46,
    "structType": "hc2c_desc",
    "group": "hc2cb",
    "kind": "HC2R",
    "radix": 8,
    "ops": {
      "add": 52,
      "mul": 18,
      "fma": 14,
      "other": 0
    },
    "via": "HC2C_VIA_RDFT"
  },
  {
    "name": "hc2cb_10",
    "registrationIndex": 47,
    "structType": "hc2c_desc",
    "group": "hc2cb",
    "kind": "HC2R",
    "radix": 10,
    "ops": {
      "add": 72,
      "mul": 30,
      "fma": 30,
      "other": 0
    },
    "via": "HC2C_VIA_RDFT"
  },
  {
    "name": "hc2cb_12",
    "registrationIndex": 48,
    "structType": "hc2c_desc",
    "group": "hc2cb",
    "kind": "HC2R",
    "radix": 12,
    "ops": {
      "add": 88,
      "mul": 30,
      "fma": 30,
      "other": 0
    },
    "via": "HC2C_VIA_RDFT"
  },
  {
    "name": "hc2cb_16",
    "registrationIndex": 49,
    "structType": "hc2c_desc",
    "group": "hc2cb",
    "kind": "HC2R",
    "radix": 16,
    "ops": {
      "add": 136,
      "mul": 46,
      "fma": 38,
      "other": 0
    },
    "via": "HC2C_VIA_RDFT"
  },
  {
    "name": "hc2cb_32",
    "registrationIndex": 50,
    "structType": "hc2c_desc",
    "group": "hc2cb",
    "kind": "HC2R",
    "radix": 32,
    "ops": {
      "add": 340,
      "mul": 114,
      "fma": 94,
      "other": 0
    },
    "via": "HC2C_VIA_RDFT"
  },
  {
    "name": "hc2cb_20",
    "registrationIndex": 51,
    "structType": "hc2c_desc",
    "group": "hc2cb",
    "kind": "HC2R",
    "radix": 20,
    "ops": {
      "add": 184,
      "mul": 62,
      "fma": 62,
      "other": 0
    },
    "via": "HC2C_VIA_RDFT"
  },
  {
    "name": "hc2cb2_4",
    "registrationIndex": 52,
    "structType": "hc2c_desc",
    "group": "hc2cb2",
    "kind": "HC2R",
    "radix": 4,
    "ops": {
      "add": 16,
      "mul": 8,
      "fma": 8,
      "other": 0
    },
    "via": "HC2C_VIA_RDFT"
  },
  {
    "name": "hc2cb2_8",
    "registrationIndex": 53,
    "structType": "hc2c_desc",
    "group": "hc2cb2",
    "kind": "HC2R",
    "radix": 8,
    "ops": {
      "add": 56,
      "mul": 26,
      "fma": 18,
      "other": 0
    },
    "via": "HC2C_VIA_RDFT"
  },
  {
    "name": "hc2cb2_16",
    "registrationIndex": 54,
    "structType": "hc2c_desc",
    "group": "hc2cb2",
    "kind": "HC2R",
    "radix": 16,
    "ops": {
      "add": 156,
      "mul": 68,
      "fma": 40,
      "other": 0
    },
    "via": "HC2C_VIA_RDFT"
  },
  {
    "name": "hc2cb2_32",
    "registrationIndex": 55,
    "structType": "hc2c_desc",
    "group": "hc2cb2",
    "kind": "HC2R",
    "radix": 32,
    "ops": {
      "add": 376,
      "mul": 168,
      "fma": 112,
      "other": 0
    },
    "via": "HC2C_VIA_RDFT"
  },
  {
    "name": "hc2cb2_20",
    "registrationIndex": 56,
    "structType": "hc2c_desc",
    "group": "hc2cb2",
    "kind": "HC2R",
    "radix": 20,
    "ops": {
      "add": 204,
      "mul": 92,
      "fma": 72,
      "other": 0
    },
    "via": "HC2C_VIA_RDFT"
  },
  {
    "name": "hc2cbdft_2",
    "registrationIndex": 57,
    "structType": "hc2c_desc",
    "group": "hc2cbdft",
    "kind": "HC2R",
    "radix": 2,
    "ops": {
      "add": 8,
      "mul": 2,
      "fma": 2,
      "other": 0
    },
    "via": "HC2C_VIA_DFT"
  },
  {
    "name": "hc2cbdft_4",
    "registrationIndex": 58,
    "structType": "hc2c_desc",
    "group": "hc2cbdft",
    "kind": "HC2R",
    "radix": 4,
    "ops": {
      "add": 24,
      "mul": 6,
      "fma": 6,
      "other": 0
    },
    "via": "HC2C_VIA_DFT"
  },
  {
    "name": "hc2cbdft_6",
    "registrationIndex": 59,
    "structType": "hc2c_desc",
    "group": "hc2cbdft",
    "kind": "HC2R",
    "radix": 6,
    "ops": {
      "add": 44,
      "mul": 14,
      "fma": 14,
      "other": 0
    },
    "via": "HC2C_VIA_DFT"
  },
  {
    "name": "hc2cbdft_8",
    "registrationIndex": 60,
    "structType": "hc2c_desc",
    "group": "hc2cbdft",
    "kind": "HC2R",
    "radix": 8,
    "ops": {
      "add": 68,
      "mul": 18,
      "fma": 14,
      "other": 0
    },
    "via": "HC2C_VIA_DFT"
  },
  {
    "name": "hc2cbdft_10",
    "registrationIndex": 61,
    "structType": "hc2c_desc",
    "group": "hc2cbdft",
    "kind": "HC2R",
    "radix": 10,
    "ops": {
      "add": 92,
      "mul": 30,
      "fma": 30,
      "other": 0
    },
    "via": "HC2C_VIA_DFT"
  },
  {
    "name": "hc2cbdft_12",
    "registrationIndex": 62,
    "structType": "hc2c_desc",
    "group": "hc2cbdft",
    "kind": "HC2R",
    "radix": 12,
    "ops": {
      "add": 112,
      "mul": 30,
      "fma": 30,
      "other": 0
    },
    "via": "HC2C_VIA_DFT"
  },
  {
    "name": "hc2cbdft_16",
    "registrationIndex": 63,
    "structType": "hc2c_desc",
    "group": "hc2cbdft",
    "kind": "HC2R",
    "radix": 16,
    "ops": {
      "add": 168,
      "mul": 46,
      "fma": 38,
      "other": 0
    },
    "via": "HC2C_VIA_DFT"
  },
  {
    "name": "hc2cbdft_32",
    "registrationIndex": 64,
    "structType": "hc2c_desc",
    "group": "hc2cbdft",
    "kind": "HC2R",
    "radix": 32,
    "ops": {
      "add": 404,
      "mul": 114,
      "fma": 94,
      "other": 0
    },
    "via": "HC2C_VIA_DFT"
  },
  {
    "name": "hc2cbdft_20",
    "registrationIndex": 65,
    "structType": "hc2c_desc",
    "group": "hc2cbdft",
    "kind": "HC2R",
    "radix": 20,
    "ops": {
      "add": 224,
      "mul": 62,
      "fma": 62,
      "other": 0
    },
    "via": "HC2C_VIA_DFT"
  },
  {
    "name": "hc2cbdft2_4",
    "registrationIndex": 66,
    "structType": "hc2c_desc",
    "group": "hc2cbdft2",
    "kind": "HC2R",
    "radix": 4,
    "ops": {
      "add": 24,
      "mul": 6,
      "fma": 6,
      "other": 0
    },
    "via": "HC2C_VIA_DFT"
  },
  {
    "name": "hc2cbdft2_8",
    "registrationIndex": 67,
    "structType": "hc2c_desc",
    "group": "hc2cbdft2",
    "kind": "HC2R",
    "radix": 8,
    "ops": {
      "add": 68,
      "mul": 18,
      "fma": 14,
      "other": 0
    },
    "via": "HC2C_VIA_DFT"
  },
  {
    "name": "hc2cbdft2_16",
    "registrationIndex": 68,
    "structType": "hc2c_desc",
    "group": "hc2cbdft2",
    "kind": "HC2R",
    "radix": 16,
    "ops": {
      "add": 168,
      "mul": 46,
      "fma": 38,
      "other": 0
    },
    "via": "HC2C_VIA_DFT"
  },
  {
    "name": "hc2cbdft2_32",
    "registrationIndex": 69,
    "structType": "hc2c_desc",
    "group": "hc2cbdft2",
    "kind": "HC2R",
    "radix": 32,
    "ops": {
      "add": 404,
      "mul": 114,
      "fma": 94,
      "other": 0
    },
    "via": "HC2C_VIA_DFT"
  },
  {
    "name": "hc2cbdft2_20",
    "registrationIndex": 70,
    "structType": "hc2c_desc",
    "group": "hc2cbdft2",
    "kind": "HC2R",
    "radix": 20,
    "ops": {
      "add": 224,
      "mul": 62,
      "fma": 62,
      "other": 0
    },
    "via": "HC2C_VIA_DFT"
  }
];
